<?php

define(PROJECTS_ALL,				0x00);
define(PROJECTS_OPEN,				0x01);
define(PROJECTS_CLOSED,				0x02);
define(IMAGES_GET_FULL, 			0x03);
define(IMAGES_GET_THUMBNAILS,		0x04);
define(IMAGES_GET_NONE,				0x05);
define(AUTHN_OK,					0x06);
define(AUTHN_FAILED,				0x07);
define(AUTHN_NOTLOGGEDIN,			0x08);
define(REGISTRATION_EMAILEXISTS,	0x09);
define(ERR_AUTHKEY_INVALID,			0x0A);
define(ERR_AUTHKEY_MISSING,			0x0B);
define(ERR_EMAIL_MISSING,			0x0C);
define(ERR_FIRSTNAME_MISSING,		0x0D);
define(ERR_LASTNAME_MISSING, 		0x0E);
define(ERR_PASSWORD1_INVALID,		0x0F);
define(ERR_PASSWORD2_INVALID,		0x10);
define(ERR_PASSWORD_UNMATCHED,		0x11);
define(ERR_EMAIL_INVALID, 			0x12);
define(ERR_PASSWORD_MISSING, 		0x13);
define(ERR_IMEI_MISSING, 			0x14);

?>